// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0PDUJNkoL8e9jN6ZQZVyXywUSillr6F8',
    appId: '1:589162349468:web:25e8d6b49a140b917e7e59',
    messagingSenderId: '589162349468',
    projectId: 'fir-77db1',
    authDomain: 'fir-77db1.firebaseapp.com',
    storageBucket: 'fir-77db1.appspot.com',
    measurementId: 'G-0S63D548PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASPgkM-gzoa5wcYsxfja1eDZz55iFw25g',
    appId: '1:589162349468:android:0a535136970732257e7e59',
    messagingSenderId: '589162349468',
    projectId: 'fir-77db1',
    storageBucket: 'fir-77db1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdCxJpvdzCKA1k1y7Q_fzfgv-f66-GVNo',
    appId: '1:589162349468:ios:ef5263bc413aa56b7e7e59',
    messagingSenderId: '589162349468',
    projectId: 'fir-77db1',
    storageBucket: 'fir-77db1.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
